### PR TITLE
Fix external app urls

### LINKED ISSUE #218: ocis-phoenix uses hardcoded `https://localhost:9200` for external app configs
There is a flag `PHOENIX_WEB_CONFIG_SERVER` in ocis-phoenix which contains the public facing URL of the hosting. We need to use that URL in the default `ExternalApps` configs in pkg/service/v0/service.go instead of the hardcoded `https://localhost:9200`.

### PR DESCRIPTION
**Pull request by kulmann**
The URLs for the default set of external apps was hardcoded to localhost:9200. We fixed that by using the server url from the already existing config variable.

Fixes https://github.com/owncloud/product/issues/218

### CODE REVIEW

File: pkg/service/v0/service.go [hunk 1]
```diff
@@ -109,6 +109,18 @@ func (p Phoenix) getPayload() (payload []byte, err error) {
...
+	aslash := strings.HasSuffix(a, "/")
+	bslash := strings.HasPrefix(b, "/")
+	switch {
+	case aslash && bslash:
+		return a + b[1:]
+	case !aslash && !bslash:
+		return a + "/" + b
+	}
+	return a + b
+}
```
Comment (refs) [inline pkg/service/v0/service.go]: Woudln't `path.Join()` do what you intend here? Check this one out: https://play.golang.org/p/zYuldrHhFXd

**Review by refs — CHANGES_REQUESTED** [review]

File: pkg/service/v0/service.go (hunk 1 above)
Comment (kulmann) [reply pkg/service/v0/service.go]: no, `path.Join` will change `http(s)://` to `http(s):/`

Comment (refs) [reply pkg/service/v0/service.go]: then the `Path` attribute should not be called Path. Instead call it it should be called URL. `https` (the protocol) is not part of the path. Different issue :)

**Review by refs — APPROVED** [review]

File: pkg/service/v0/service.go (hunk 1 above)
Comment (kulmann) [reply pkg/service/v0/service.go]: Wow, I was just thinking `we would have to rename the key in phoenix then... wait, maybe it can be used as a path?!`. That works as well. Updating the PR...

**Comment by refs** [comment]
LGTM :)
